// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Lyric(arg1:number):Promise<main.LyricDTO>;

export function Pause():Promise<void>;

export function PlaySong(arg1:number):Promise<void>;

export function Resume():Promise<void>;

export function Search(arg1:string):Promise<Array<main.SongDTO>>;

export function Seek(arg1:number):Promise<void>;

export function SetVolume(arg1:number):Promise<void>;

export function Status():Promise<main.PlayerStatus>;

export function Stop():Promise<void>;

export function Toggle():Promise<void>;

export function Volume():Promise<number>;

export function VolumeDown():Promise<number>;

export function VolumeUp():Promise<number>;
