// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Lyric(arg1) {
  return window['go']['main']['App']['Lyric'](arg1);
}

export function Pause() {
  return window['go']['main']['App']['Pause']();
}

export function PlaySong(arg1) {
  return window['go']['main']['App']['PlaySong'](arg1);
}

export function Resume() {
  return window['go']['main']['App']['Resume']();
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function Seek(arg1) {
  return window['go']['main']['App']['Seek'](arg1);
}

export function SetVolume(arg1) {
  return window['go']['main']['App']['SetVolume'](arg1);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function Toggle() {
  return window['go']['main']['App']['Toggle']();
}

export function Volume() {
  return window['go']['main']['App']['Volume']();
}

export function VolumeDown() {
  return window['go']['main']['App']['VolumeDown']();
}

export function VolumeUp() {
  return window['go']['main']['App']['VolumeUp']();
}
