// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function AlbumSongs(arg1:number):Promise<Array<app.SongDTO>>;

export function LoadSession():Promise<app.SessionState>;

export function LoadState():Promise<app.LocalState>;

export function Lyric(arg1:number):Promise<app.LyricDTO>;

export function Pause():Promise<void>;

export function PlaySong(arg1:number):Promise<app.PlaySongResult>;

export function PlaylistSongs(arg1:number):Promise<Array<app.SongDTO>>;

export function Resume():Promise<void>;

export function SaveSession(arg1:app.SessionState):Promise<void>;

export function SaveState(arg1:app.LocalState):Promise<void>;

export function Search(arg1:string,arg2:string,arg3:number):Promise<app.SearchResp>;

export function Seek(arg1:number):Promise<void>;

export function SetVolume(arg1:number):Promise<void>;

export function Status():Promise<app.PlayerStatus>;

export function Stop():Promise<void>;

export function Toggle():Promise<void>;

export function Volume():Promise<number>;

export function VolumeDown():Promise<number>;

export function VolumeUp():Promise<number>;
