// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AlbumSongs(arg1) {
  return window['go']['app']['App']['AlbumSongs'](arg1);
}

export function LoadSession() {
  return window['go']['app']['App']['LoadSession']();
}

export function LoadState() {
  return window['go']['app']['App']['LoadState']();
}

export function Lyric(arg1) {
  return window['go']['app']['App']['Lyric'](arg1);
}

export function Pause() {
  return window['go']['app']['App']['Pause']();
}

export function PlaySong(arg1) {
  return window['go']['app']['App']['PlaySong'](arg1);
}

export function PlaylistSongs(arg1) {
  return window['go']['app']['App']['PlaylistSongs'](arg1);
}

export function Resume() {
  return window['go']['app']['App']['Resume']();
}

export function SaveSession(arg1) {
  return window['go']['app']['App']['SaveSession'](arg1);
}

export function SaveState(arg1) {
  return window['go']['app']['App']['SaveState'](arg1);
}

export function Search(arg1, arg2, arg3) {
  return window['go']['app']['App']['Search'](arg1, arg2, arg3);
}

export function Seek(arg1) {
  return window['go']['app']['App']['Seek'](arg1);
}

export function SetVolume(arg1) {
  return window['go']['app']['App']['SetVolume'](arg1);
}

export function Status() {
  return window['go']['app']['App']['Status']();
}

export function Stop() {
  return window['go']['app']['App']['Stop']();
}

export function Toggle() {
  return window['go']['app']['App']['Toggle']();
}

export function Volume() {
  return window['go']['app']['App']['Volume']();
}

export function VolumeDown() {
  return window['go']['app']['App']['VolumeDown']();
}

export function VolumeUp() {
  return window['go']['app']['App']['VolumeUp']();
}
